### ISSUE TITLE
Overflowed pins no longer embedding images

### ISSUE THREAD

**Issue by DPS2004** [OblivionCreator/Bulletin-Board#2]
At some in mid to late august, the webhook for overflowed pins stopped embedding attatched images alongside the message.

An old message, showing the expected behavior:
![image](https://github.com/OblivionCreator/Bulletin-Board/assets/10176105/2af559a2-e3c6-41e8-a254-13f812b26a33)

The first example of a message failing to embed in this way that I could find:
![image](https://github.com/OblivionCreator/Bulletin-Board/assets/10176105/2310a8b9-2990-4719-948e-21ff0b4c0931)

I'm not sure if this is related and I don't expect that it's fixable, but its worth mentioning that some older messages no longer display the avatar of the user *inside* of the embed, though the webhook avatar works fine. 
![image](https://github.com/OblivionCreator/Bulletin-Board/assets/10176105/71ce2503-106e-416c-8805-e0096acbf076)

**Comment by OblivionCreator** [comment]
Older pins no longer displaying avatar inside the embed is likely due to that user changing their avatar later on - The bot just feeds the users' avatar URL into there (It also does this for the PFP, but I think Discord just downloads & reuploads the image in this case, making a new link)

Without either hosting the avatars myself or using a separate discord server to store avatars, there's no good way to fix this.

Embed breaking is interesting to me - The bot fetches embeds directly from the `discord.Message` object, so this seems to imply that the messages have no embeds in the Message Obj (which makes little sense...)

Thanks for the report - I'll take a look

**Comment by OblivionCreator** [comment]
Resolved in [af1a6b1](https://github.com/OblivionCreator/Bulletin-Board/commit/af1a6b1b8f1a72b7cee16a70d77e80479a323a50)
